### ISSUE TITLE
RunWrite unexpected return value

### ISSUE THREAD

**Issue by nylar** [rethinkdb/rethinkdb-go#140]
When running a query with RunWrite that fails, one would expect error to be an error, instead it is nil and one must inspect the contents of WriteResponse for any errors making the error return parameter somewhat useless.

The query in question is:

res, err := rdb.Db(Database).Table(IndexTable).Insert(indexes).RunWrite(session)

When inserting two objects with duplicate ids, it returns an error that can be accessed through res but err is nil.

**Comment by dancannon** [comment]
This is actually intentional. While this might not make sense initially, if you look at what RethinkDB is actually returning your query did not completely fail. The initial object being inserted was written to the database correctly, however the second object did not get written so the `FirstError` field contains an error explaining this. Does this make sense?

That being said it might make sense to add a `Successful` method to the `WriteResponse` which checks if the query was completely successful. I will look into adding this in the next version.

**Comment by nylar** [comment]
Yes that makes perfect sense Daniel, just was odd that I had to check for any errors through res instead of error especially when doing seperate writes. So the first one would naturally succeed but the second would return an error in res but err would be nil. However, doing the below isn't too bad just a little confusing:

``` go
if res.Errors > 0 { return errors.New(res.FirstError) }
```

Might just need some explaining in the docs.
