### ISSUE TITLE
Is panic expected behaviour when passing a nil session to RunWrite

### ISSUE THREAD

**Issue by alimoeeny** [rethinkdb/rethinkdb-go#155]
I know I shouldn't pass a nil session to RunWrite or any other function for that matter, but is panic the expected behaviour? Or there is a way to return an error or something?

**Comment by dancannon** [comment]
While this isnt a major issue since as you mention you really shouldnt be passing nil into Run I will look into returning in error if you try to do so. 

I will look into this when I get back from my holiday some time next week.

**Comment by alimoeeny** [comment]
Thanks, sure, no rush.

**Comment by dancannon** [comment]
Sorry to go back on my word but I am going to close this issue, as mentioned I dont think its a very serious issue since you should always be properly checking for errors when connecting.

Unfortunately I have limited time to work on the driver so I need to spend this time on the higher priority issues.
