### ISSUE TITLE
Connect fails to single server

### ISSUE THREAD

**Issue by lamielle** [rethinkdb/rethinkdb-go#175]
Recent changes related to clustering and auto-discovery seem to have broken connection code which worked in 0.6.x.  Details:

```
var err error
session, err = gorethink.Connect(gorethink.ConnectOpts{
        Address:  "localhost:28015",
        Database: "database",
        MaxIdle: 10,
        Timeout: time.Second * 10,
})
if err != nil {
        return err
}
```

Using this pattern worked in 0.6.x.  I recently updated to the latest gorethink sources in master and found that connecting to the localhost RethinkDB instance produces the following error:

```
2015/04/15 11:50:55.781453 Failure setting up RethinkDB: no connections were made when creating the session
```

I see that a new 'Addresses' field is available.  I've tried that with a slice of the single "localhost:28015" string but I receive the same error.

Is master known to be unstable and shouldn't be used?  If not, is this bug known?

Finally, unrelated, but I see a few typos in the new documentation that mentions 'Addresses' usage.  'Conenct' is misspelled and there is a trailing "localhost:28015" which was not reverted when the API was changed.

**Comment by dancannon** [comment]
Hi, sorry to hear you are having issues, The master branch should be stable and the host discovery changes has been in the develop branch (which is the unstable branch) for a couple of weeks. Unfortunately due to the way go get works very few people actually use this branch so its difficult to get feedback without releasing to master. 

That being said I have tested these changes (thanks for pointing out the typos in the documentation) and not come across this bug but I will start looking into this now. Would you be able to answer a couple of questions to help debugging:
- Which version of RethinkDB are you using? (GoRethink v0.7 only supports RethinkDB 2.0)
- How many nodes are in your cluster?
- Do you still have the same issue if you downgrade the driver to v0.6.3?

**Comment by lamielle** [comment]
That explains it then: my local version is RethinkDB 1.16.2-1 (which was installed via Homebrew).

Deployed in staging/production: both have 3 nodes.  These environments also are running 1.16.x.  However, I have a container running rethinkdb in proxy mode which my application container connects to.  This simplified the application logic.

I have pinned the gorethink to hash a05fb9f684e7bcf6ada71ff71b8b73ba28e63a6a which is what the 0.6.x and 0.6.3 tags point at.  When reverting to this commit connections work just fine.

However, is there a reason not to support connecting to 1.16.x DBs with the newer code?  I suspect many people will want support for this.  For users of gorethink which haven't vendored (or otherwise pinned the code) I suspect this will be a very surprising change for them.  It was for me.

Thanks for looking into this and for such a quick response!

**Comment by lamielle** [comment]
One more note: if supporting 1.16.x on master is not an option, it seems at a minimum a better error message (explicit version check?) would really help to avoid surprises like this.  Thanks again.

**Comment by dancannon** [comment]
Its times like this I wish Go had proper package management, but we probably shouldnt start that discussion :D

I have not looked into this issue just yet but I imagine it is because v0.7 uses a different RethinkDB protocol version. It would seem that the two are not compatible. That being said I will have a look and see if I can get the driver to work with older database versions.

Regarding you point about providing better error checking I am not sure that is possible due to how the driver protocol works but at the very least I will add a notice to the README explaining that the latest version of the driver doesnt support older database versions. Also I hope this RethinkDB will not break backwards compatibility for a while now that RethinkDB 2.0 has been released.

I will keep this issue open until I have fully investigated the use with older versions but I will remove the high priority flag. Thanks again for reporting the issue.

**Comment by lamielle** [comment]
Oh yes, that discussion has been beaten to death.  I'm really surprised a community hasn't grown up that mimics something like Ruby's package versioning.  Vendoring is fine but to me seems inappropriate in some situations.

The README update will help, definitely.  I'll keep pinned to 0.6.x for now and update to newer code once I've upgrade all my servers to 2.0.  Thanks!

**Comment by dancannon** [comment]
I had a look at running the driver with an older version of RethinkDB but it seems the protocols are completely incompatible. I have added some logging to the driver and better documented the limitation in the readme. 

Thanks again for opening the issue.

**Comment by lamielle** [comment]
Ok, that's unfortunate.  Thank you for looking into it!

Do you know if the same is true for RethinkDB 1.16 binaries talking to a 2.0 server?  I would hope that I could update my core DB nodes first, and the proxy nodes I use to route requests to the three DB servers could remain on 1.16 for a short time.  Once the core DB servers are updated I'd update the proxy nodes.  Otherwise, there's little hope of zero downtime...

Not complaining to you, just curious if you had any experience with a setup like this.

**Comment by dancannon** [comment]
Basically this is just because I upgraded the to use the v0.4 protocol which was new to RethinkDB 2.0. However RethinkDB 2.0 still supports the old protocols so you should be able to downgrade gorethink to a version <= 0.6.x which used the v0.3 protocol, upgrade all nodes to RethinkDB to 2.0 and then upgrade gorethink to the latest version. I think that should work but I am not quite sure about your setup with proxy nodes.

I know its a bit of a pain but I am not sure if there is anyway around it.

**Comment by lamielle** [comment]
Ok, that's good info.  I unfortunately haven't read up on the various protocol versions.  I have 3 core DB nodes running plus each of my API server nodes runs a rethinkdb process in 'proxy' mode which the application on each of the API server nodes connects to (rather than directly to the DB servers).  This simplified my application logic/deployment.

My migration path to 2.0 will then be as you suggest: upgrade all 3 DB nodes (the proxy processes on each API server node running 1.16 will still work against the 2.0 server).  Upgrade one of my API server nodes by upgrading my application to use the latest gorethink AND the proxy node to speak protocol v0.4.  I can roll this same upgrade across all API server nodes one by one.

Anyway, probably more detail than you care about, but maybe it will be useful to understand how I'm using gorethink and RethinkDB.  Thanks again!

**Comment by dancannon** [comment]
Definitely not, its interesting to see how different people are using RethinkDB in production. If you have any more questions get in touch (https://gitter.im/dancannon/gorethink might be a good place to send me questions)
