### ISSUE TITLE
Using Term in Merge function causes error "Variable name not found"

### ISSUE THREAD

**Issue by daniel-nichter** [rethinkdb/rethinkdb-go#196]
I want to do a one-to-many join and merge like:

``` js
r.db('bug').table('class').merge(function (doc) {
    return {
      students: r.db('bug').table('student').getAll( r.args(doc('studentNames')) ).coerceTo('array')
    }
}).without('studentNames');
```

In general terms, I'm trying to merge `doc1.names` on `doc2.names` but put the matching `doc2` results into `doc1.otherField`, which is why I'm merging instead of just joining.

That ReQL query above works, but the Go equivalent does not:

``` go
type Student struct {
    Name     string `gorethink:"name"`
    RealName string `gorethink:"fullName"`
}

type Class struct {
    Name     string    `gorethink:"name"`
    Students []Student `gorethink:"students"`
}

type T struct { // how to merge only Students in Class?
    Students []Student
}

    res, err := r.Table("class").Merge(func(row r.Term) interface{} {
        // BUG: this does not work:
        res, err := r.Table("student").GetAll(r.Args(row.Field("studentNames"))).Run(session)
        // But this does:
        //res, err := r.Table("student").GetAll("jack", "jill", "mike", "ike").Run(session)
        if err != nil {
            log.Fatal(err)
        }
        var students []Student
        res.All(&students)
        return T{students}
    }).Without("studentNames").Run(session)
```

That causes:

```
2015/06/01 18:09:39 gorethink: Variable name not found. in: 
r.Table("student").GetAll(r.Args(var_0.Field("studentNames")))
```

To reproduce, here's the trivial data (`class` table then `student` table):

``` json
[
  {"name": "1st grade", "studentNames": ["jack", "jill"]},
  {"name": "2nd grade", "studentNames": ["mike", "ike"]}
]

[
  {"fullName": "Ike A.", "name": "ike"},
  {"fullName": "Jack J.", "name": "jack"},
  {"fullName": "Jill J.", "name": "jill"},
  {"fullName": "Mike M.", "name": "mike"}
]
```

Perhaps my Go code is wrong? Or there's another way to do this? I can't find an example of `Merge()` with a func.

**Comment by dancannon** [comment]
Hi @daniel-nichter, Instead of running the query inside your merge function you should instead return the query). By running the queries inside the merge function you are actually causing separate calls to the database.

For example you query should look like this instead:

``` go
cur, err := r.Table("class").Merge(func(row r.Term) interface{} {
    return map[string]interface{}{
        "students": r.Table("student").GetAll(r.Args(row.Field("studentNames"))).CoerceTo("array"),
    }
}).Without("studentNames").Run(s)
if err != nil {
    log.Fatal(err.Error())
}

var res []interface{}
if err := cur.All(&res); err != nil {
    log.Fatal(err.Error())
}
```

Hopefully this answers your question, if you have any further questions let me know.

**Comment by dancannon** [comment]
Also thanks for the detailed example, It really helps!

**Comment by daniel-nichter** [comment]
Yes, your query works. Thanks @dancannon!

I can add an example to the docs, but I see https://github.com/dancannon/gorethink/pull/186 is waiting on fixtures, so perhaps I should wait for that PR?

**Comment by dancannon** [comment]
Great! I have actually added more examples recently in this branch https://github.com/dancannon/gorethink/tree/feature/examples however I dont have any examples for `Merge` or using a function callback that returns a map. I can add an example to this branch before merging.

I will close this issue for now since I think I think we have answered the original question, feel free to reopen if needed.
