### ISSUE TITLE
Timeout on  >>func (c *Cursor) Next(dest interface{}) bool<<

### ISSUE THREAD

**Issue by jaracil** [rethinkdb/rethinkdb-go#205]
It will be useful for change feeds to add a timeout on Next method, like python driver.

http://www.rethinkdb.com/api/python/next/

Example:

``` go
func (c *Cursor) Next(dest interface{}, optArgs ...NextOpts) bool

type NextOpts struct {
    Wait        bool // false -> no wait, true -> wait until new data arrive or Timeout expires
    Timeout     Duration // Zero Value -> wait for ever
}
```

Thanks.

**Comment by kofalt** [comment]
FWIW, you can get that behaviour today with [ `time.After`](https://golang.org/pkg/time/#After):

``` go
select {
    case m := <-c:
        fmt.Println("got item")

    case <-time.After(5 * time.Second):
        fmt.Println("timed out")
}
```

**Comment by jaracil** [comment]
In some cases you don't need to keep open the feed after the timeout. In this case the goroutine that executes Next() method could block forever.
One option would be close the cursor in another goroutine, so the blocked goroutine wakes up. Will this work?

**Comment by kofalt** [comment]
Hmm, not sure. I don't think cursors are goroutine-safe for concurrent access, but a close shouldn't matter since no data would be consumed. Specifically, I think in the case of a timeout you'd want to close both the cursor and the reporting channel (in my example, `c`).

I'll defer to Dan for an authoritative response & decision on if a timeout option should be added to `Next`, or maybe a separate `NextWait` that just takes a `time.Duration`.

**Comment by dancannon** [comment]
Closing the cursor should be possible, I have used it in the past to stop a changefeed query. I hope to make the cursor goroutine-safe in the near future. 

I am not too sure about the addition of options to Next at the moment, I think that closing the Cursor is more flexible especially if you use the `Listen` function to listen for changefeeds.

**Comment by omeid** [comment]
:+1:

**Comment by dancannon** [comment]
I am closing this issue since I have updated `Cursor`s to be safe for concurrent use in v1.1 and I think the methods discussed above should solve most use cases.
