### ISSUE TITLE
Option for disabling logging

### ISSUE THREAD

**Issue by ftKnox** [rethinkdb/rethinkdb-go#222]
It would be great to have the ability to disable logging completely. I use your driver in a cli tool and when there are issues it pollutes the display with log statements. Otherwise, love the driver, thanks for building it.

i.e. "WARN[0011] Error creating connection dial tcp 192.168.1.100:28015: getsockopt: network is unreachable"

**Comment by dancannon** [comment]
Since the Logger is exposed as `Log` it should be possible to set the output of the logger to `ioutil.Discard`. For example

``` go
r.Log.SetOutput(ioutil.Discard)
```

A helper function could be added to the driver but I think this method is a bit simpler, however I will look into adding some instructions to the README explaining this process and the SetVerbose function. What do you think?

**Comment by ftKnox** [comment]
Sorry, I was using v1.1.1 which didn't have r.log exported. I see that v1.1.2 does. Your proposed solution sounds fine to me.

**Comment by dancannon** [comment]
Sounds good, thanks for the suggestion and for using the driver :) I will keep this issue open until I update the README.

**Comment by ftKnox** [comment]
Just checked andn r.Log.SetOutput() doesn't actually work. SetOutput() is not a method on *logrus.Logger, so I had to do:

```
r.Log.Out = ioutil.Discard
```

**Comment by dancannon** [comment]
Ah ok, thanks for letting me know!

**Comment by dancannon** [comment]
I now have updated the readme in master. Thanks for the suggestion.
