### ISSUE TITLE
Ignore omitempty when update

### ISSUE THREAD

**Issue by alehano** [rethinkdb/rethinkdb-go#228]
Hi. I have a field with `gorethink:",omitempty"`.
It works fine when I create a new record. But If I filled this field and later I want to remove data from it by save as empty string, it doesn't work, because field ignored. I just can replace field data by another data, not empty string.
It seems like expected behaviour, but what can I do in my scenario?

**Comment by ghost** [comment]
@alehano Looks like #86 is related.

**Comment by dancannon** [comment]
As @anonx pointed out using `Update` with a map is the best way to solve your issue. You could also use an anonymous struct.

**Comment by alehano** [comment]
It's not the best solution. I marshal/unmarshal my struct. And I want to have regular struct with types rather than map of interfaces.

**Comment by dancannon** [comment]
This is the exact same way that `encoding/json` works,  I am not sure how else it could work.

**Comment by alehano** [comment]
I preferred not to use omitempty and just have unnecessary empty fields in DB. But, it's make me sad, of course.

**Comment by alehano** [comment]
Sorry. Maybe I didn't understand where I sould use map? Should I replace my stuct with map. But how can I use it in my app? Check fields types and so on.

**Comment by alehano** [comment]
Oh, sorry. I catched it. I have to pass map only to Update method. Ok, I'll try.

**Comment by alehano** [comment]
But anyway it'll be great to have a tag for delete field if it's empty.

**Comment by ghost** [comment]
> it'll be great to have a tag for delete field if it's empty. 

@alehano There is such a tag, it is called `omitempty`. But as you have already pointed out it doesn't work the way you want. The driver has no idea whether `Bio` in your structure below is empty ("") because you want it to be empty or it is empty ("") because you want to ignore it to update `Age` only.

``` go
type User struct {
    Age int
    Bio string
}
```

Though you can use pointers just as @nimajalali proposed https://github.com/dancannon/gorethink/issues/86#issuecomment-42871034 in the issue I linked above. Then it will be clear for gorethink whether you expect empty string ("") or you want to ignore the field (nil).

I have settled on `type Data map[string]interface{}` option for updates.

**Comment by dancannon** [comment]
I think we can close this issue now, if you have any other questions feel free to reopen or create a new issue.
