### ISSUE TITLE
Panic when calling Cursor.Next()

### ISSUE THREAD

**Issue by DanielHeckrath** [rethinkdb/rethinkdb-go#230]
We observed a panic on a call to Cursor.Next()

```
panic: sync: Unlock of unlocked RWMutex
goroutine 21 [running]:
github.com/dancannon/gorethink.(*Cursor).Next()
/usr/src/go/src/sync/rwmutex.go:114
sync.(*RWMutex).Unlock()
/go/src/github.com/dancannon/gorethink/cursor.go:160
```

To me it seems that the mutex might be unlocked, if Cursor.fetchMore() returns an error in line 186.

**Comment by dancannon** [comment]
Thanks for reporting this, I will try to find some time to fix it later today.

Just a note for myself since I am at work at the moment, this is the line that is causing the issue, the mutex should be locked after the call to `fetchMore`. https://github.com/dancannon/gorethink/blob/master/cursor.go#L186

**Comment by dancannon** [comment]
Merged to master.
