### ISSUE TITLE
Deleting Map Key doesn't result in Update

### ISSUE THREAD

**Issue by timshannon** [rethinkdb/rethinkdb-go#243]
Take a look at this gist https://gist.github.com/timshannon/d23fd0ee9fe427b034f2

Am I doing something wrong?  I can't seem to figure out how to delete a key out of a map and have it updated.

It seems to me like a bug, but I may be doing something incorrect.

Thanks,

**Comment by timshannon** [comment]
Oh and I'm running against gorethink 1.1.4

**Comment by dancannon** [comment]
Hi @timshannon, `Update` works a little differently to what you are assuming, instead of setting the document to exactly what you passed in it instead merges the document already stored with the document you passed in. The reason that RethinkDB does this is that it allows for partial updates.

The following query should do what you want:

``` go
res, err = rt.Table(table).Get(key).Replace(rt.Row.Without(map[string]interface{}{
    "Map": map[string]interface{}{
        "testmapkey": true,
    },
})).RunWrite(session)
```

**Comment by timshannon** [comment]
Sorry, yep you're right.  Looks like I need to change some assumptions I made about how / where I'm using update.

Thanks,

**Comment by dancannon** [comment]
Not a problem, any further questions feel free to post a message in gitter/slack or create another issue.
