### ISSUE TITLE
Add examples for each query

### ISSUE THREAD

**Issue by elithrar** [rethinkdb/rethinkdb-go#27]
Chris did a fantastic job of this with http://godoc.org/github.com/christopherhesse/rethinkgo (every RQL operation has a basic example above it) and I think we could do a similarly fantastic job.

I'm opening an issue for this as a prompt for others to contribute/as a "to do" item to flesh out the documentation.

I plan to work on this proper once my schedule frees up mid November, but I'll be chipping away at this when I can as I move my (as yet unfinished!) side-project over to this driver.

**Comment by dancannon** [comment]
I agree this is something that needs to be sorted out. If you could work on this when you have some time that would be great. 

Unfortunately I am busy with other work at the moment so I am trying to prioritise what I spend my time on. Hopefully I will have some time soon so I can help out on this as well.

Also I think it might be good if we keep the examples in the proper format so that they display properly on the GoDocs. For more info check out the Examples section here http://golang.org/pkg/testing/

**Comment by dancannon** [comment]
I have added a couple of examples using the technique mentioned on this page http://golang.org/pkg/testing/. It seems pretty good as running `go test` also tests the examples. 

You can view the examples on the godoc page.

**Comment by dancannon** [comment]
Just to update this issue, I have not had a lot of time lately so this issue has been pushed back. That being said I plan to properly document all functions for the 1.0 release and ensure that the package passes govet/golint.

**Comment by dancannon** [comment]
I have spent some time updating documentation for version 1.0 but it is still not as good as it should be. Unfortunately I do not have enough time to get this sorted before the RethinkDB 2.0 release so I am going to postpone this to v1.1.

**Comment by dancannon** [comment]
With help from @MattAitchison I have added a number of examples (using the standard Godoc example format). Although it's not quite at the level of each query having an example it is a good start therefore I will close this issue for now. I hope to continue adding more examples in the future.
