### ISSUE TITLE
EOF error in cluster

### ISSUE THREAD

**Issue by deviantmk** [rethinkdb/rethinkdb-go#282]
Hello

While running in a cluster if one machine goes down during writes, the driver reports an EOF

I was trying to check if any data loss would happen and it did, so far only 1 record was missing but i will do some more stress tests

**Comment by dancannon** [comment]
Hi, GoRethink does not do any retries so if there is an error while writing a document then that write will not be successful. If you wanted to make sure is no data loss (or at least reduce the chance) then perhaps you could retry the query in your application.

**Comment by deviantmk** [comment]
Thanks for the answer i hope we can discuss this

If the query has an error then yes, but if the query fail due to a machine failure, the cluster is of no use this way. This is no query error so the driver should take care of it in case of a machine failure.

there should be some sort of a check and if the machine is not reachable it should auto re-route it to the next ip in the cluster.

Sadly I dont know the protocol and i have no ability to check how the official drivers handle this. If someone can, it would be nice.

**Comment by gabeio** [comment]
~~:-1: sorry the driver should NOT do anything more than report back that there was an error. As this is how rethink works including in other languages, I have to say that this should be dropped back on the application to decide what to do not the driver to continuously retry until the machine comes back online.~~

**Comment by deviantmk** [comment]
@gabeio you misunderstood

The driver should not retry, the driver should redirect the query to an available machine.
Are you suggesting that we should pollute our app and add a specific error check after every query just to see if one machine in the cluster had failed?

Its a cluster, its high availability... which right now this driver does not support.

**Comment by deviantmk** [comment]
@dancannon @gabeio

I just did the same tests with the python driver, it does not happen at all.
This driver is not production ready and needs to be fixed asap, starting from the EOF thing which is not even an error

**Comment by dancannon** [comment]
I am not sure what you mean by when you say that the python driver does not have this issue, from what I can see the python driver does not do any retries at all so I dont see how the behaviour could be any different. Also what do you mean "EOF" is not an error, when the connection is dropped because the server dies and EOF will be returned. I fail to see how this is not an error.

When you say that the driver "should redirect the query to an available machine" this is still a retry, currently the driver will retry with the same connection but not to a different machine.

Regardless if a write fails with an error the data is not lost, it was never acknowledged. Either the driver or your application could retry the write but it results in the same behaviour.

**Comment by deviantmk** [comment]
Hi
For now it would be good if a proper error can be returned instead of an EOF, I have read a bit about the driver specification

ReqlOpIndeterminateError 
Cannot perform write: lost contact with primary replica

something like this will do for now and the rest we can leave it open for discussion in case someone else wants to join

**Comment by dancannon** [comment]
All connection errors should be wrapped by the `RQLConnectionError`, this should do what you want. I will close this for now as I dont think there there are any changes that need to be made to GoRethink currently.
