### ISSUE TITLE
connection fail 

### ISSUE THREAD

**Issue by blackss2** [rethinkdb/rethinkdb-go#328]
I got this message when i didn't use connection for a long time(30m ~ 1h).
- Error Message
  gorethink: read tcp _CLIENT_IP_:52873->_SERVER_IP_:28015: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

After this message was shown, I restart my server and request same query. This restarting action make query to act right way. It is not occurred in my another productions that is not using any Changes() feature, but use normal query. And this another productions was not applied commit after Mar 31 2016.

I prepare answer using #317 issue.

**Has this only started happening recently?** => Yes I never seen this issue before. I got this message from commit [Re-enabled keep alive by default].
**Which version of RethinkDB and GoRethink are you using?** => Always recent version I use.(rethinkDB 2.3)
**What does your Connect look like?** => This issue only occured when I sit off long time(minimum 30m~1 hour). So I think connection was lost and do not recovered automatically.

Thanks for reading.

**Comment by dancannon** [comment]
Thanks for reporting this issue, I have not been able to replicate this yet however that is just because I have not had time to test running a test for more than 30 mins. That being said I may have a possible solution bc4ba832a7682762ac2357aea1fdd9903d8fb33f. 

Essentially queries should be retried if they fail due to a bad connection error, however due to a bug this did not happen if you executed your query using `Query()`. I will do more tests when I have time but I hope this fixes your issue.

**Comment by dancannon** [comment]
Released fix in `v2.0.4`
