### ISSUE TITLE
Mocking inserts

### ISSUE THREAD

**Issue by pzduniak** [rethinkdb/rethinkdb-go#346]
Hey, I'm struggling with mocking - I am inserting a document with a randomly-generated ID and I can't mock it, because I can't anyhow predict the ID. Any tips on how to do that?

**Comment by dancannon** [comment]
Unfortunately this is not possible as the current implementation of the mocking utility only supports mocking exact queries (this is due to the simple way the library compares queries). I plan to make mocking more flexible but I am not sure when I will have time to work on this as there are a couple of other features that I am trying to finish first. That being said I have created the issue https://github.com/dancannon/gorethink/issues/347 where I have added a bit more information and will update whenever I get round to working on mocking again.

I will also close this issue and keep the discussion in the linked issue to try and keep things clear, if you have any further questions just ask :)
