### ISSUE TITLE
Decode blanking struct values

### ISSUE THREAD

**Issue by klaidliadon** [rethinkdb/rethinkdb-go#352]
If I try to execute this snippet, `dst.AnotherField` get wiped out. Is this expected?

``` go
package main

import (
    "fmt"

    "gopkg.in/dancannon/gorethink.v2/encoding"
)

func main() {
    var dst struct {
        Field        string
        AnotherField string
    }
    dst.Field = "change me"
    dst.AnotherField = "don't blank me"
    err := encoding.Decode(&dst, map[string]interface{}{"Field": "Changed!"})
    if err != nil {
        panic(err)
    }
    fmt.Printf("%+v", dst)
}
```

Outputs: 

```
{Field:Changed! AnotherField:}
```

**Comment by dancannon** [comment]
This is the expected behaviour due to the normal use case for the encoding package which is to be used with `Next`, for example in the code below you would want the contents of `dst` to be zeroed each time to prevent data from the previous iteration being left in the struct.

``` go
package main

...

func main() {
    var dst struct {
        Field        string
        AnotherField string
    }
    for res.Next(&dst) {
        fmt.Printf("%+v", dst)
    }
}
```

This could possibly be made configurable if required but the default behaviour cant change at the moment.

**Comment by klaidliadon** [comment]
Please take a look at this and tell me if it's a viable approach:

https://github.com/klaidliadon/gorethink/commit/078b2edbadcabeb2a4df024d8875ca6c0f12f1a3

**Comment by dancannon** [comment]
Looks good to me 👍 Thanks for making this change, if possible could you add some tests and create a PR?
