### ISSUE TITLE
Storage encoding question

### ISSUE THREAD

**Issue by jpillora** [rethinkdb/rethinkdb-go#379]
I have two use cases:
- Simple backup/restore (fetch all rows, store in a file/load from file, store all rows)
- Offline mode (hash query `Term.String() string`, store results in a file, indexed by hash, use this file when `!session.IsConnected()`)

What format would you recommend for storing query results in a generic way?

**Comment by jpillora** [comment]
I was going to simply use JSON, though my structs have `json` tags are adapted for public consumption and have `gorethink` tags for internal consumption and I'd like to use the `gorethink` view (database view) of the data. My solution this was to use `map[string]interface{}` instead, though it understandably won't decode`time.Time` strings or encode `[]byte` as base64 strings. So, the best way I can think of is to recursively perform this kinds of type conversions against the resulting `map`. I was hoping there was an intermediate structure I could use, like the protobuff structs, though it looks like there's no clean way to do that...

**Comment by thomasmodeneis** [comment]
Hi @jpillora 
1) The official driver is doing it with python and they are just storing json in a temp folder, I'm not expert in py but you can read the code to have an idea https://github.com/rethinkdb/rethinkdb/blob/next/drivers/python/rethinkdb/_dump.py

2) What do you want is something like https://pouchdb.com/ ? 
They did something really nice because the way couchdb is build it has versions and the master/sync architecture takes care of the merges, how do you plan to do this ?

Cheers.

**Comment by jpillora** [comment]
Hi @thomasmodeneis 
1. Storing JSON in a temp folder could work though `gorethink` encodes the raw rethinkdb JSON into strings for some types `time.Time` and `[]byte`, whereas I'd like to have  `{"$reql_type$":"TIME","epoch_time":1478570181.254,"timezone":"+00:00"}` and `{"$reql_type$":"BINARY","data":"qmcwhUpa"}`
2. I think that'd be overkill for what I need. At its core, I just need the underlying encoding, unfiltered by struct tags.

I think I'll just fork this package and add what I need

**Comment by dancannon** [comment]
Hi @jpillora, the driver actually contains some methods for accessing the raw responses from RethinkDB which might be useful for you. 

https://godoc.org/github.com/dancannon/gorethink#Cursor.NextResponse
