### ISSUE TITLE
Can't 'go get' this package

### ISSUE THREAD

**Issue by adamveld12** [rethinkdb/rethinkdb-go#385]
I'm using go 1.7.3 on darwin/amd64

When I tried doing `go get -v gopkg.in/dancannon/gorethink.v2` it fails when pulling down `gopkg.in/fatih/pool.v2`. The following is the output:

```
Fetching https://gopkg.in/fatih/pool.v2?go-get=1
Parsing meta tags from https://gopkg.in/fatih/pool.v2?go-get=1 (status code 200)
get "gopkg.in/fatih/pool.v2": found meta tag main.metaImport{Prefix:"gopkg.in/fatih/pool.v2", VCS:"git", RepoRoot:"https://gopkg.in/fatih/pool.v2"} at https://gopkg.in/fatih/pool.v2?go-get=1
gopkg.in/fatih/pool.v2 (download)
# cd .; git clone https://gopkg.in/fatih/pool.v2 /Users/Adam/projects/go/src/gopkg.in/fatih/pool.v2
Cloning into '/Users/Adam/projects/go/src/gopkg.in/fatih/pool.v2'...
fatal: unable to access 'https://gopkg.in/fatih/pool.v2/': Unknown SSL protocol error in connection to gopkg.in:-9838
package gopkg.in/fatih/pool.v2: exit status 128
```

Using `go get -v -insecure  gopkg.in/dancannon/gorethink.v2` gives me the same error as above. 

However, when I run the git clone manually over HTTP (not HTTPS) like so, it succeeds:

```
git clone http://gopkg.in/fatih/pool.v2 Users/Adam/projects/go/src/github.com/adamveld12/hookspy/vendor/gopkg.in/fatih/pool.v2
Cloning into 'Users/Adam/projects/go/src/github.com/adamveld12/hookspy/vendor/gopkg.in/fatih/pool.v2'...
remote: Counting objects: 193, done.
remote: Total 193 (delta 0), reused 0 (delta 0), pack-reused 193
Receiving objects: 100% (193/193), 34.39 KiB | 0 bytes/s, done.
Resolving deltas: 100% (109/109), done.
```

**Comment by thomasmodeneis** [comment]
Hi,

I'm not sure if this is a problem of the package itself, it looks to me more of a go get thing.

Right now because of the vendor experiment and all the changes on this topic, including the namespaces for packages and so on I would avoid concluding anything so fast.

Have you tried go getting the package with the github name ? so github.com/dancannon/gorethink ?

Cheers.

**Comment by adamveld12** [comment]
Yeah I tried doing `go get -v github.com/dancannon/gorethink` and got the same error:

```
Fetching https://gopkg.in/fatih/pool.v2?go-get=1
Parsing meta tags from https://gopkg.in/fatih/pool.v2?go-get=1 (status code 200)
get "gopkg.in/fatih/pool.v2": found meta tag main.metaImport{Prefix:"gopkg.in/fatih/pool.v2", VCS:"git", RepoRoot:"https://gopkg.in/fatih/pool.v2"} at https://gopkg.in/fatih/pool.v2?go-get=1
gopkg.in/fatih/pool.v2 (download)
# cd .; git clone https://gopkg.in/fatih/pool.v2 /Users/Adam/projects/go/src/gopkg.in/fatih/pool.v2
Cloning into '/Users/Adam/projects/go/src/gopkg.in/fatih/pool.v2'...
fatal: unable to access 'https://gopkg.in/fatih/pool.v2/': Unknown SSL protocol error in connection to gopkg.in:-9838
package gopkg.in/fatih/pool.v2: exit status 128
```

It's strange to me that `go get -insecure` didn't clone that package over HTTP, which could be a bug in go get but I'm not sure. The [documentation on `go get -insecure` is very skimp](https://golang.org/cmd/go/#hdr-Download_and_install_packages_and_dependencies).

It's also strange that `git clone` chokes on `https://gopkg.in/fatih/pool.v2` but not the HTTP variant, so it seems like there is also something up with gopkg.in's SSL setup but _only_ for `gopkg.in/fatih/pool.v2`. Other packages from gopkg.in pull down just fine.

So yeah, I don't know what to think about this either. If no one else can reproduce it then its probably just me but I figured I'd let the maintainers be aware of it since it _could_ affect others using this package.

**Comment by thomasmodeneis** [comment]
Very recently I ran into problems to update gorethink and I also had problems with this very same lib, however I got a different error:

```
package gopkg.in/dancannon/gorethink.v2/encoding: exit status 1
# cd /opt/gocode/src/gopkg.in/fatih/pool.v2; git pull --ff-only
You are not currently on a branch. Please specify which
branch you want to merge with. See git-pull(1) for details.

    git pull <remote> <branch>

package gopkg.in/fatih/pool.v2: exit status 1
```

I've raised this issue on the golang-nuts mail list and I have been completely ignored.
The main issue here is that google does not really care about this, because their internal package management system works in another way, so I guess you will have to raise your concerns on the mail list or on the golang git in order to understand how this works and maybe find out how to fix it.

This is the thread of the problem I had and how I managed to work around it:
https://groups.google.com/forum/#!topic/golang-nuts/t9dLLVwsMlM

Cheers.

**Comment by adamveld12** [comment]
Awesome, thanks. I'll close this issue since I have a work around but if I find out more I'll post it here if that's fine.
