### ISSUE TITLE
r.Table(name).Update(entity) does not work when passing a struct

### ISSUE THREAD

**Issue by konradreiche** [rethinkdb/rethinkdb-go#407]
The following issue became apparent when there are at least two entities in the table and you create a struct from scratch and pass it to `Update` like this:

```Go
user = &User{ID: "2", Username: "bar"}
r.Table(userTable).Update(user).RunWrite(db)
```

Will lead to:

```
Primary key `id` cannot be changed (`{
                        "id":   "1",
                        "username": "foo",
                }` -> `{
                        "id":   "2",
                        "username": "bar",
                }`).
```
Which is a bit strange, since the passed user has id `"2"` and it was not intended to replace the other document. What does work is the following though:

```Go
r.Table(userTable).Get(user.ID).Update(user).RunWrite(db)
```

I tried to step a little bit through the source code but did not fully understand from where this discrepancy originates. I also translated the the whole `Term` by printing it with `String()` and used the raw query in the RethinkDB console, which was successful, too.

**Comment by cemmurphy** [comment]
I'm super new to Golang but I've been using RethinkDB for some time and I think what you have here is just a misunderstanding of the RethinkDB semantics / syntax.

Your first query:  `r.Table('userTable'').Update(user)` is asking to "update EVERYTHING in 'userTable' with the values in user". Hence the error about the primary key. This would be similar to an accidental SQL update with no where clause. BTW, this syntax is the same for the JS, Python, etc. RethinkDB clients.

Your second query is the proper way to update a known, single object / row by primary key / id. You can sort of think of the "Get" as the SQL where clause part of your update, keeping you from updating every object in the table. You could also do `..Filter..Update` instead of a Get to limit your update.

Hope this helps.

**Comment by konradreiche** [comment]
That makes a lot of sense. Thanks for clarifying!
