### ISSUE TITLE
gorethink support for RethinkDB 2.4

### ISSUE THREAD

**Issue by sankethpb** [rethinkdb/rethinkdb-go#438]
RethinkDB 2.4 is about to be released.
Could you please let us know if this support is planned?

**Comment by CMogilko** [comment]
Yes, I plan to support protocol changes if any, when protocol changes will be documented.

**Comment by thelinuxlich** [comment]
We've forked RethinkDB as RebirthDB because of lack of development and communication from the founders, discussion here: https://spectrum.chat/rebirthdb

Things are already in motion to release a 2.4 version, would you like to join our organization? We are separating all drivers in their own repositories.

**Comment by thomasmodeneis** [comment]
Hi @thelinuxlich 
Yes, we want to join in rebirthdb and become official driver, finally. 
How is the process to join in ?

Cheers.

**Comment by CMogilko** [comment]
2.4 support implemented in the next branch. Will not be merged until 2.4 deb pkg appears. Travis CI depends on it.
